### ISSUE TITLE
Не работает основной скрипт, выдаёт ошибки

### ISSUE THREAD

**Issue by artemandrushko** [shalkov/DuolingoHackExperience#1]
Exception in thread Thread 2:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\lbicb\PycharmProjects\DuolingoHackExperience\main.py", line 17, in my_timer
    send_requests()
  File "C:\Users\lbicb\PycharmProjects\DuolingoHackExperience\main.py", line 8, in send_requests
    myId = data["id"]
           ~~~~^^^^^^
TypeError: 'NoneType' object is not subscriptable
HTTP Request failed

**Comment by st-man** [comment]
Подтверждаю. От версии python не зависит. Пробовал 3.8.6, 3.10.5 и 3.12.3
Точно такие-же ошибки.

**Comment by artemandrushko** [comment]
> Подтверждаю. От версии python не зависит. Пробовал 3.8.6, 3.10.5 и 3.12.3 Точно такие-же ошибки.

Я проверил на маке и там всё работает. На винде так и продолжает не работать.

**Comment by D8nley** [comment]
> Exception in thread Thread 2: Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1073, in _bootstrap_inner self.run() File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1010, in run self._target(*self._args, **self._kwargs) File "C:\Users\lbicb\PycharmProjects\DuolingoHackExperience\main.py", line 17, in my_timer send_requests() File "C:\Users\lbicb\PycharmProjects\DuolingoHackExperience\main.py", line 8, in send_requests myId = data["id"] ~~~~^^^^^^ TypeError: 'NoneType' object is not subscriptable HTTP Request failed

такая же проблема на мак буке
